### PR TITLE
start declaring the 'global' chain with module resources

### PR DESCRIPTION
**Pull request by lelutin**
the 'global' chain is a vestigial piece of early development on this
module, but it can be useful for creating fast short-circuits like
blocking traffic that match a certain set of IPs.

in the current state we can't inject rules inside the 'global' chain
since it's unknown to puppet. so let's remove the hard-coded definition
and use a puppet resource to declare it.

### CODE REVIEW

**Comment by nbarrientos** [comment]
Sound good. Could perhaps some extra test coverage be added to `spec/classes/inet_filter_spec.rb` at the same time to make sure that the chain is created and cover regressions?

**Comment by duritong** [comment]
yeah, let's add a spec and merge.

**Comment by lelutin** [comment]
@nbarrientos ah yes good point, I forgot to add tests. I've just sent the added tests, let's see how CI likes them (at least locally they were failing on the master branch and successful on top of this branch)

**Review by nbarrientos — APPROVED** [review]
LGTM

**Review by duritong — APPROVED** [review]

**Comment by duritong** [comment]
thank you!

**Pull request merged**
